import { Template, TemplateCategory } from './types';

export const MOCK_TEMPLATES: Template[] = [
  {
    id: '1',
    title: 'SaaS Rocket Launch',
    author: 'PixelCrafters',
    price: 49,
    rating: 4.8,
    sales: 1240,
    category: TemplateCategory.SAAS,
    image: 'https://picsum.photos/800/600?random=1',
    tags: ['Conversion', 'Dark Mode', 'React'],
    description: 'A high-converting landing page designed specifically for SaaS startups launching on Product Hunt.',
  },
  {
    id: '2',
    title: 'Influencer Viral Bio',
    author: 'TrendSetters',
    price: 19,
    rating: 4.5,
    sales: 8500,
    category: TemplateCategory.VIRAL,
    image: 'https://picsum.photos/800/600?random=2',
    tags: ['Mobile First', 'Link in Bio', 'Fast'],
    description: 'The ultimate link-in-bio replacement. Loads in under 0.5s. Perfect for TikTok and Instagram traffic.',
  },
  {
    id: '3',
    title: 'Agency Portfolio Pro',
    author: 'DesignGurus',
    price: 79,
    rating: 4.9,
    sales: 320,
    category: TemplateCategory.AGENCY,
    image: 'https://picsum.photos/800/600?random=3',
    tags: ['Elegant', 'Animation', 'Portfolio'],
    description: 'Showcase your agency work with stunning GSAP animations and a clean, modern aesthetic.',
  },
  {
    id: '4',
    title: 'E-Com Drop Killer',
    author: 'CommerceKing',
    price: 39,
    rating: 4.6,
    sales: 2100,
    category: TemplateCategory.ECOM,
    image: 'https://picsum.photos/800/600?random=4',
    tags: ['Shopify', 'High CTR', 'Sales'],
    description: 'Aggressive sales funnel structure designed for dropshipping products. Proven to increase CR by 20%.',
  },
  {
    id: '5',
    title: 'Crypto Dark Nex',
    author: 'BlockChainViz',
    price: 59,
    rating: 4.7,
    sales: 890,
    category: TemplateCategory.SAAS,
    image: 'https://picsum.photos/800/600?random=5',
    tags: ['Web3', 'Crypto', 'Futuristic'],
    description: 'Deep dark UI with neon accents, perfect for Web3, DAO, and NFT projects.',
  },
  {
    id: '6',
    title: 'Minimalist Blogger',
    author: 'WriteSimple',
    price: 25,
    rating: 4.8,
    sales: 560,
    category: TemplateCategory.BLOGGER,
    image: 'https://picsum.photos/800/600?random=6',
    tags: ['Clean', 'Typography', 'SEO'],
    description: 'Focus on content. Ultra-fast loading speed and perfect typography for serious writers.',
  },
];

export const PENDING_TEMPLATES: Template[] = [
  {
    id: 'p1',
    title: 'NFT Minting Engine',
    author: 'Web3Master',
    price: 89,
    rating: 0,
    sales: 0,
    category: TemplateCategory.SAAS,
    image: 'https://picsum.photos/800/600?random=10',
    tags: ['Web3', 'Minting'],
    description: 'Complete minting dApp template pending security review.',
  },
  {
    id: 'p2',
    title: 'High Ticket Coach Funnel',
    author: 'FunnelHacker',
    price: 199,
    rating: 0,
    sales: 0,
    category: TemplateCategory.VIRAL,
    image: 'https://picsum.photos/800/600?random=11',
    tags: ['Funnel', 'Coaching'],
    description: 'Long form sales letter template for coaches.',
  }
];

export const REVENUE_DATA = [
  { name: 'Jan', value: 4000 },
  { name: 'Feb', value: 3000 },
  { name: 'Mar', value: 2000 },
  { name: 'Apr', value: 2780 },
  { name: 'May', value: 1890 },
  { name: 'Jun', value: 2390 },
  { name: 'Jul', value: 3490 },
  { name: 'Aug', value: 5200 },
  { name: 'Sep', value: 6100 },
  { name: 'Oct', value: 7800 },
  { name: 'Nov', value: 9000 },
  { name: 'Dec', value: 11500 },
];

export const CATEGORY_DATA = [
  { name: 'SaaS', value: 400 },
  { name: 'Viral', value: 300 },
  { name: 'Agency', value: 300 },
  { name: 'E-Com', value: 200 },
];