import { Template, TemplateCategory } from './types';

export const MOCK_TEMPLATES: Template[] = [
  {
    id: '1',
    title: 'Nexus AI – Ultimate Admin Dashboard & Landing Page System',
    author: 'CommerceCloud',
    price: 89,
    rating: 4.9,
    sales: 4120,
    category: TemplateCategory.ADMIN_SAAS,
    image: 'https://picsum.photos/800/600?random=1',
    tags: ['Next.js', 'Bento Grid', 'Tokens'],
    description: 'The ultimate design system for 2026 SaaS. Bento Grid aesthetic, AI token monitoring, and instant Dark Mode switch. Launch your MVP in days, not months.',
  },
  {
    id: '2',
    title: 'Cyber Sentinel – Real-time Security & SOC Dashboard',
    author: 'SecurityFirst',
    price: 149,
    rating: 4.8,
    sales: 1100,
    category: TemplateCategory.ADMIN_SAAS,
    image: 'https://picsum.photos/800/600?random=2',
    tags: ['Cybersecurity', 'React', 'Live Stats'],
    description: 'Professional-grade SOC monitoring. Stop threats with real-time heatmaps, automated compliance reporting, and frosted glass UI.',
  },
  {
    id: '3',
    title: 'E-Comm Growth Pro – AI-Driven Predictive Analytics',
    author: 'PixelCrafters',
    price: 79,
    rating: 4.9,
    sales: 5200,
    category: TemplateCategory.ECOM_DASHBOARD,
    image: 'https://picsum.photos/800/600?random=3',
    tags: ['Shopify', 'ROAS', 'Predictive'],
    description: 'Revenue-first Shopify dashboard. Track ROAS, predict churn, and optimize retention with "Product-as-Proof" widgets.',
  },
  {
    id: '4',
    title: 'Marketing Ops Hero',
    author: 'AdTechGurus',
    price: 59,
    rating: 4.7,
    sales: 2800,
    category: TemplateCategory.MARKETING_DASHBOARD,
    image: 'https://picsum.photos/800/600?random=4',
    tags: ['Facebook Ads', 'Google Ads', 'ROI'],
    description: 'Centralize all your marketing data. ROI tracking for multiple platforms in one unified view.',
  },
  {
    id: '5',
    title: 'Multipurpose Ultra Pro',
    author: 'DesignSystems',
    price: 129,
    rating: 5.0,
    sales: 850,
    category: TemplateCategory.MULTIPURPOSE,
    image: 'https://picsum.photos/800/600?random=5',
    tags: ['Vast', 'Modern', 'Design System'],
    description: 'Elite multipurpose admin framework with 500+ components and 50+ unique page layouts.',
  },
  {
    id: '6',
    title: 'Agency Funnel V3',
    author: 'TrendSetters',
    price: 49,
    rating: 4.6,
    sales: 1560,
    category: TemplateCategory.AGENCY,
    image: 'https://picsum.photos/800/600?random=6',
    tags: ['GSAP', 'Agency', 'Modern'],
    description: 'High-end agency landing page with sophisticated animations and proof sections.',
  },
];

export const PENDING_TEMPLATES: Template[] = [
  {
    id: 'p1',
    title: 'DEX Liquidity Panel',
    author: 'Web3Master',
    price: 149,
    rating: 0,
    sales: 0,
    category: TemplateCategory.CRYPTO_DASHBOARD,
    image: 'https://picsum.photos/800/600?random=10',
    tags: ['Yield', 'Crypto'],
    description: 'Monitoring tool for LP positions on Uniswap and Curve. Pending audit.',
    createdAt: '2026-05-10',
  },
  {
    id: 'p2',
    title: 'Coaching CRM Lite',
    author: 'FunnelHacker',
    price: 79,
    rating: 0,
    sales: 0,
    category: TemplateCategory.ADMIN_SAAS,
    image: 'https://picsum.photos/800/600?random=11',
    tags: ['CRM', 'Coaching'],
    description: 'Simplified SaaS admin for individual coaches managing monthly cohorts.',
    createdAt: '2026-05-11',
  }
];

export const REVENUE_DATA = [
  { name: 'Jan', value: 4000 },
  { name: 'Feb', value: 3000 },
  { name: 'Mar', value: 2000 },
  { name: 'Apr', value: 2780 },
  { name: 'May', value: 1890 },
  { name: 'Jun', value: 2390 },
  { name: 'Jul', value: 3490 },
  { name: 'Aug', value: 5200 },
  { name: 'Sep', value: 6100 },
  { name: 'Oct', value: 7800 },
  { name: 'Nov', value: 9000 },
  { name: 'Dec', value: 11500 },
];

export const CATEGORY_DATA = [
  { name: 'SaaS Admin', value: 500 },
  { name: 'E-Comm', value: 400 },
  { name: 'Crypto', value: 300 },
  { name: 'Marketing', value: 200 },
];
